# Generated by Django 5.1.1 on 2024-10-29 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_cantidad'),
        ('productos', '0002_alter_producto_categoria_alter_producto_estado'),
    ]

    operations = [
    ]
