# Generated by Django 5.1.1 on 2024-11-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_merge_20241029_1856'),
        ('productos', '0005_alter_producto_cantidad'),
    ]

    operations = [
    ]
