# Generated by Django 5.1.1 on 2024-10-24 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_pedido_insumos_iteminsumo_recepcionpedidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminsumo',
            name='precio',
        ),
    ]
