# Generated by Django 5.1.1 on 2024-10-24 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
    ]
