# Generated by Django 5.1.1 on 2024-10-26 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_remove_pedido_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminsumo',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='pedidos.pedido'),
        ),
    ]
