# Generated by Django 5.1.1 on 2024-10-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionpedidos',
            name='precio_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
