# Generated by Django 5.1.1 on 2024-10-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_alter_recepcionpedidos_conformidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminsumo',
            name='unidad_medida',
            field=models.CharField(blank=True, choices=[('Unidades', 'u'), ('Gramos', 'g'), ('Kilogramos', 'Kg'), ('Mililitros', 'ml'), ('Litros', 'L')], max_length=10),
        ),
    ]
