# Generated by Django 5.1.1 on 2024-10-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_iteminsumo_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminsumo',
            name='cantidad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='iteminsumo',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
