# Generated by Django 5.1.1 on 2024-10-31 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_fecha_pedido'),
        ('pedidos', '0012_alter_iteminsumo_cantidad_and_more'),
    ]

    operations = [
    ]
