# Generated by Django 5.1.1 on 2024-11-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_insumo_cantidad'),
        ('pedidos', '0013_merge_20241031_0100'),
    ]

    operations = [
    ]
