# Generated by Django 5.1.1 on 2024-11-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_merge_20241101_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='cantidad_minima',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
