# Generated by Django 5.1.1 on 2024-11-02 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_alter_insumo_cantidad_minima'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestarInsumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_medida', models.CharField(blank=True, max_length=10)),
                ('cantidad_restar', models.FloatField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.insumo')),
            ],
        ),
    ]
