# Generated by Django 5.1.1 on 2024-11-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_restarinsumos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminsumo',
            name='unidad_medida',
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
