# Generated by Django 5.1.1 on 2024-11-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_empleado_tipo_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil_usuario',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Vendedor', 'Vendedor'), ('Almacenero', 'Almacenero'), ('Gerente', 'Gerente')], max_length=50),
        ),
    ]
