# Generated by Django 5.1.2 on 2024-10-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='FechaVenta',
            field=models.DateField(),
        ),
    ]
