# Generated by Django 5.1.2 on 2024-10-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_fechaventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='numeroComprobante',
            field=models.CharField(),
        ),
    ]
