# Generated by Django 5.1.2 on 2024-10-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_venta_numerocomprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='numeroComprobante',
            field=models.CharField(max_length=15),
        ),
    ]
