# Generated by Django 5.1.2 on 2024-10-27 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_mayorista_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemMayorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mayorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.mayorista')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
        ),
    ]
