# Generated by Django 5.1.2 on 2024-10-27 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_itemmayorista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmayorista',
            old_name='mayorista',
            new_name='mayorista_cuit',
        ),
    ]
