# Generated by Django 5.1.1 on 2024-10-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_rename_mayorista_itemmayorista_mayorista_cuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
