# Generated by Django 5.1.1 on 2024-11-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_itemproducto_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mayorista',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(max_length=15),
        ),
    ]
